/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/auth/login": {
    /** Login */
    post: operations["login_api_auth_login_post"];
  };
  "/api/auth/refresh": {
    /** Refresh */
    post: operations["refresh_api_auth_refresh_post"];
  };
  "/api/auth/logout": {
    /** Logout */
    post: operations["logout_api_auth_logout_post"];
  };
  "/api/auth/me": {
    /** Me */
    get: operations["me_api_auth_me_get"];
  };
  "/api/auth/me/password": {
    /** Change My Password */
    put: operations["change_my_password_api_auth_me_password_put"];
  };
  "/api/auth/admins": {
    /** List Admins */
    get: operations["list_admins_api_auth_admins_get"];
    /** Create Admin */
    post: operations["create_admin_api_auth_admins_post"];
  };
  "/api/auth/admins/{admin_id}": {
    /** Delete Admin */
    delete: operations["delete_admin_api_auth_admins__admin_id__delete"];
    /** Update Admin */
    patch: operations["update_admin_api_auth_admins__admin_id__patch"];
  };
  "/api/users": {
    /** List Users */
    get: operations["list_users_api_users_get"];
  };
  "/api/users/{account}": {
    /** Get User */
    get: operations["get_user_api_users__account__get"];
  };
  "/api/users/sync-ad": {
    /**
     * Trigger Ad Sync
     * @description Trigger an incremental AD sync (async — returns immediately).
     *
     * The sync runs in a tracked background task on its own session so the
     * request is not held open and failures are logged. Poll
     * ``GET /api/users/sync-records`` to track progress.
     */
    post: operations["trigger_ad_sync_api_users_sync_ad_post"];
  };
  "/api/users/sync-records": {
    /**
     * List Sync Records
     * @description List AD sync job history (latest first).
     */
    get: operations["list_sync_records_api_users_sync_records_get"];
  };
  "/api/users/sync-records/{job_id}": {
    /**
     * Get Sync Record
     * @description Detail of a single AD sync job (includes error text).
     */
    get: operations["get_sync_record_api_users_sync_records__job_id__get"];
  };
  "/api/users/status": {
    /** Update User Status */
    post: operations["update_user_status_api_users_status_post"];
  };
  "/api/users/policy": {
    /** Assign User Policy */
    post: operations["assign_user_policy_api_users_policy_post"];
  };
  "/api/policies": {
    /** List Policies */
    get: operations["list_policies_api_policies_get"];
    /** Create Policy */
    post: operations["create_policy_api_policies_post"];
  };
  "/api/policies/{policy_id}": {
    /** Get Policy */
    get: operations["get_policy_api_policies__policy_id__get"];
    /** Update Policy */
    put: operations["update_policy_api_policies__policy_id__put"];
    /** Delete Policy */
    delete: operations["delete_policy_api_policies__policy_id__delete"];
    /** Toggle Policy */
    patch: operations["toggle_policy_api_policies__policy_id__patch"];
  };
  "/api/policies/reorder": {
    /** Reorder Policies */
    post: operations["reorder_policies_api_policies_reorder_post"];
  };
  "/api/devices/nas": {
    /** List Nas */
    get: operations["list_nas_api_devices_nas_get"];
    /** Create Nas */
    post: operations["create_nas_api_devices_nas_post"];
  };
  "/api/devices/nas/{device_id}": {
    /** Delete Nas */
    delete: operations["delete_nas_api_devices_nas__device_id__delete"];
    /** Update Nas */
    patch: operations["update_nas_api_devices_nas__device_id__patch"];
  };
  "/api/devices/nas/{device_id}/secret": {
    /** Reveal Nas Secret */
    get: operations["reveal_nas_secret_api_devices_nas__device_id__secret_get"];
  };
  "/api/devices/nas/{device_id}/ports": {
    /** Nas Ports */
    get: operations["nas_ports_api_devices_nas__device_id__ports_get"];
  };
  "/api/devices/nas/{device_id}/ssids": {
    /** Nas Ssids */
    get: operations["nas_ssids_api_devices_nas__device_id__ssids_get"];
  };
  "/api/devices/endpoints": {
    /** List Endpoints */
    get: operations["list_endpoints_api_devices_endpoints_get"];
    /** Create Endpoint */
    post: operations["create_endpoint_api_devices_endpoints_post"];
  };
  "/api/devices/endpoints/{mac}": {
    /** Update Endpoint */
    patch: operations["update_endpoint_api_devices_endpoints__mac__patch"];
  };
  "/api/devices/endpoints/import": {
    /** Import Endpoints */
    post: operations["import_endpoints_api_devices_endpoints_import_post"];
  };
  "/api/devices/endpoints/{mac}/whitelist": {
    /** Remove From Whitelist */
    delete: operations["remove_from_whitelist_api_devices_endpoints__mac__whitelist_delete"];
  };
  "/api/devices/endpoints/{mac}/revoke-cert": {
    /** Revoke Endpoint Cert */
    post: operations["revoke_endpoint_cert_api_devices_endpoints__mac__revoke_cert_post"];
  };
  "/api/sessions": {
    /** List Sessions */
    get: operations["list_sessions_api_sessions_get"];
  };
  "/api/sessions/export.csv": {
    /** Export Sessions Csv */
    get: operations["export_sessions_csv_api_sessions_export_csv_get"];
  };
  "/api/sessions/{acct_unique_id}": {
    /** Get Session */
    get: operations["get_session_api_sessions__acct_unique_id__get"];
  };
  "/api/sessions/disconnect": {
    /** Disconnect Sessions */
    post: operations["disconnect_sessions_api_sessions_disconnect_post"];
  };
  "/api/sessions/reauthorize": {
    /**
     * Reauthorize Sessions
     * @description Bulk CoA-Request to trigger re-authorization (docs/01 批量 CoA).
     */
    post: operations["reauthorize_sessions_api_sessions_reauthorize_post"];
  };
  "/api/auth-logs": {
    /** List Logs */
    get: operations["list_logs_api_auth_logs_get"];
  };
  "/api/auth-logs/export.csv": {
    /** Export Logs Csv */
    get: operations["export_logs_csv_api_auth_logs_export_csv_get"];
  };
  "/api/auth-logs/{log_id}": {
    /** Get Log */
    get: operations["get_log_api_auth_logs__log_id__get"];
  };
  "/api/dashboard/kpis": {
    /** Get Kpis */
    get: operations["get_kpis_api_dashboard_kpis_get"];
  };
  "/api/dashboard/trend": {
    /** Get Trend */
    get: operations["get_trend_api_dashboard_trend_get"];
  };
  "/api/dashboard/alerts": {
    /** Get Alerts */
    get: operations["get_alerts_api_dashboard_alerts_get"];
  };
  "/api/dashboard/alerts/{alert_id}/read": {
    /** Read Alert */
    post: operations["read_alert_api_dashboard_alerts__alert_id__read_post"];
  };
  "/api/reports/summary": {
    /** Report Summary */
    get: operations["report_summary_api_reports_summary_get"];
  };
  "/api/reports/endpoint-types": {
    /** Report Endpoint Types */
    get: operations["report_endpoint_types_api_reports_endpoint_types_get"];
  };
  "/api/reports/departments": {
    /** Report Departments */
    get: operations["report_departments_api_reports_departments_get"];
  };
  "/api/reports/export": {
    /** Report Export */
    get: operations["report_export_api_reports_export_get"];
  };
  "/api/settings": {
    /** Get Settings */
    get: operations["get_settings_api_settings_get"];
    /** Update Settings */
    put: operations["update_settings_api_settings_put"];
  };
  "/api/settings/alert-rules": {
    /** Get Alert Rules */
    get: operations["get_alert_rules_api_settings_alert_rules_get"];
    /** Update Alert Rules */
    put: operations["update_alert_rules_api_settings_alert_rules_put"];
  };
  "/api/audit": {
    /** List Audit */
    get: operations["list_audit_api_audit_get"];
  };
  "/api/audit/export.csv": {
    /**
     * Export Audit Csv
     * @description CSV archive of audit log entries (docs/08「审计日志」归档导出).
     */
    get: operations["export_audit_csv_api_audit_export_csv_get"];
  };
  "/api/health": {
    /** Health */
    get: operations["health_api_health_get"];
  };
  "/api/metrics": {
    /**
     * Metrics
     * @description Prometheus metrics exporter — reserved (docs/07「M7 之后可选」).
     */
    get: operations["metrics_api_metrics_get"];
  };
  "/api/ops/reload-radius": {
    /**
     * Reload Radius
     * @description Restart FreeRADIUS so rlm_sql re-reads the nas table (docs/06).
     *
     * ``read_clients`` only loads at startup, so client changes need a restart.
     * Runs ``OPENRADIUS_RADIUS_RELOAD_COMMAND`` when configured; otherwise
     * responds in manual mode with instructions.
     */
    post: operations["reload_radius_api_ops_reload_radius_post"];
  };
  "/api/ops/compile": {
    /**
     * Compile
     * @description Idempotent full recompile of policy/user state into the radius schema.
     */
    post: operations["compile_api_ops_compile_post"];
  };
  "/api/portal": {
    /** Portal Root */
    get: operations["_portal_root_api_portal_get"];
    /** Portal Root */
    put: operations["_portal_root_api_portal_get"];
    /** Portal Root */
    post: operations["_portal_root_api_portal_get"];
    /** Portal Root */
    delete: operations["_portal_root_api_portal_get"];
    /** Portal Root */
    patch: operations["_portal_root_api_portal_get"];
  };
  "/api/portal/{path}": {
    /** Portal Catch All */
    get: operations["_portal_catch_all_api_portal__path__get"];
    /** Portal Catch All */
    put: operations["_portal_catch_all_api_portal__path__get"];
    /** Portal Catch All */
    post: operations["_portal_catch_all_api_portal__path__get"];
    /** Portal Catch All */
    delete: operations["_portal_catch_all_api_portal__path__get"];
    /** Portal Catch All */
    patch: operations["_portal_catch_all_api_portal__path__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * AdSyncJobOut
     * @description Single AD sync job record.
     */
    AdSyncJobOut: {
      /** Id */
      id: number;
      /** Triggered By */
      triggered_by: string;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      /** Finished At */
      finished_at: string | null;
      /** Status */
      status: string;
      /** Added */
      added: number;
      /** Updated */
      updated: number;
      /** Disabled */
      disabled: number;
      /** Error */
      error: string | null;
    };
    /**
     * AdSyncResult
     * @description Immediate response from POST /api/users/sync-ad.
     */
    AdSyncResult: {
      /** Triggered */
      triggered: boolean;
      /** Message */
      message: string;
    };
    /** AdminCreate */
    AdminCreate: {
      /** Username */
      username: string;
      /**
       * Display Name
       * @default
       */
      display_name?: string;
      /** Password */
      password?: string | null;
      /** Linked Account */
      linked_account?: string | null;
      /** @default operator */
      role?: components["schemas"]["AdminRole"];
    };
    /** AdminOut */
    AdminOut: {
      /** Id */
      id: number;
      /** Username */
      username: string;
      /** Display Name */
      display_name: string;
      role: components["schemas"]["AdminRole"];
      status: components["schemas"]["AdminStatus"];
      /** Linked Account */
      linked_account?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** AdminProfile */
    AdminProfile: {
      /** Username */
      username: string;
      /** Display Name */
      display_name: string;
      /** Role */
      role: string;
    };
    /**
     * AdminRole
     * @enum {string}
     */
    AdminRole: "admin" | "operator" | "auditor";
    /**
     * AdminStatus
     * @enum {string}
     */
    AdminStatus: "active" | "disabled";
    /** AdminUpdate */
    AdminUpdate: {
      /** Display Name */
      display_name?: string | null;
      role?: components["schemas"]["AdminRole"] | null;
      status?: components["schemas"]["AdminStatus"] | null;
      /** Password */
      password?: string | null;
    };
    /** Affected */
    Affected: {
      /** Affected */
      affected: number;
    };
    /** AlertRuleIn */
    AlertRuleIn: {
      /** Key */
      key: string;
      /** Enabled */
      enabled: boolean;
      /** Threshold */
      threshold?: {
        [key: string]: unknown;
      };
    };
    /** AlertRuleOut */
    AlertRuleOut: {
      /** Key */
      key: string;
      /** Enabled */
      enabled: boolean;
      /** Threshold */
      threshold: {
        [key: string]: unknown;
      };
    };
    /** AlertRulesUpdate */
    AlertRulesUpdate: {
      /** Rules */
      rules: components["schemas"]["AlertRuleIn"][];
    };
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      /** Old Password */
      old_password: string;
      /** New Password */
      new_password: string;
    };
    /**
     * Compliance
     * @enum {string}
     */
    Compliance: "ok" | "warn" | "bad" | "white";
    /** DisconnectFailure */
    DisconnectFailure: {
      /** Id */
      id: string;
      /** Reason */
      reason: string;
    };
    /** DisconnectRequest */
    DisconnectRequest: {
      /** Session Ids */
      session_ids: string[];
      /**
       * Confirm
       * @default false
       */
      confirm?: boolean;
    };
    /** DisconnectResult */
    DisconnectResult: {
      /** Disconnected */
      disconnected: number;
      /** Failed */
      failed: components["schemas"]["DisconnectFailure"][];
    };
    /**
     * EapMethod
     * @enum {string}
     */
    EapMethod: "eap-tls" | "peap-mschapv2";
    /** EndpointBrief */
    EndpointBrief: {
      /** Mac */
      mac: string;
      /** Etype */
      etype: string;
      /** Compliance */
      compliance: string;
      /** Whitelisted */
      whitelisted: boolean;
    };
    /** EndpointCreate */
    EndpointCreate: {
      /**
       * Fingerprint
       * @default
       */
      fingerprint?: string;
      /** Owner Account */
      owner_account?: string | null;
      /** @default other */
      etype?: components["schemas"]["EndpointType"];
      /** @default ok */
      compliance?: components["schemas"]["Compliance"];
      /**
       * Comp Detail
       * @default
       */
      comp_detail?: string;
      /**
       * Whitelisted
       * @default false
       */
      whitelisted?: boolean;
      /** Mac */
      mac: string;
    };
    /** EndpointImport */
    EndpointImport: {
      /** Macs */
      macs: string[];
    };
    /** EndpointOut */
    EndpointOut: {
      /**
       * Fingerprint
       * @default
       */
      fingerprint?: string;
      /** Owner Account */
      owner_account?: string | null;
      /** @default other */
      etype?: components["schemas"]["EndpointType"];
      /** @default ok */
      compliance?: components["schemas"]["Compliance"];
      /**
       * Comp Detail
       * @default
       */
      comp_detail?: string;
      /**
       * Whitelisted
       * @default false
       */
      whitelisted?: boolean;
      /** Id */
      id: number;
      /** Mac */
      mac: string;
      /** Owner Name */
      owner_name: string | null;
      /** Cert Not After */
      cert_not_after: string | null;
      /** First Seen At */
      first_seen_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * EndpointType
     * @enum {string}
     */
    EndpointType: "laptop" | "phone" | "printer" | "camera" | "other";
    /** EndpointUpdate */
    EndpointUpdate: {
      /**
       * Fingerprint
       * @default
       */
      fingerprint?: string;
      /** Owner Account */
      owner_account?: string | null;
      /** @default other */
      etype?: components["schemas"]["EndpointType"];
      /** @default ok */
      compliance?: components["schemas"]["Compliance"];
      /**
       * Comp Detail
       * @default
       */
      comp_detail?: string;
      /**
       * Whitelisted
       * @default false
       */
      whitelisted?: boolean;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LogDetailOut */
    LogDetailOut: {
      /** Id */
      id: number;
      /**
       * Time
       * Format: date-time
       */
      time: string;
      /** User */
      user: string;
      /** Name */
      name: string;
      /** Sub */
      sub: string;
      /** Mac */
      mac: string;
      /** Nas */
      nas: string;
      /** Nas Name */
      nas_name: string;
      /** Nas Sub */
      nas_sub: string;
      /** Eap */
      eap: string;
      /** Reply */
      reply: string;
      /** Reason */
      reason?: string | null;
      /** Reason Key */
      reason_key?: string | null;
      /** Rtag Tone */
      rtag_tone?: string | null;
      /** Attr */
      attr: string;
      /** Attributes */
      attributes: {
        [key: string]: unknown;
      };
    };
    /** LoginRequest */
    LoginRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** LogoutRequest */
    LogoutRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** NasCreate */
    NasCreate: {
      /** Name */
      name: string;
      /** Nasname */
      nasname: string;
      /** @default switch */
      type?: components["schemas"]["NasType"];
      /**
       * Area
       * @default
       */
      area?: string;
      /** Capacity */
      capacity?: number | null;
      /**
       * Baseline Enabled
       * @default true
       */
      baseline_enabled?: boolean;
      /**
       * Notes
       * @default
       */
      notes?: string;
      /** Secret */
      secret: string;
    };
    /** NasOut */
    NasOut: {
      /** Name */
      name: string;
      /** Nasname */
      nasname: string;
      /** @default switch */
      type?: components["schemas"]["NasType"];
      /**
       * Area
       * @default
       */
      area?: string;
      /** Capacity */
      capacity?: number | null;
      /**
       * Baseline Enabled
       * @default true
       */
      baseline_enabled?: boolean;
      /**
       * Notes
       * @default
       */
      notes?: string;
      /** Id */
      id: number;
      /** Secret Masked */
      secret_masked: string;
      /** Radius Nas Id */
      radius_nas_id: number | null;
      /**
       * Status
       * @default offline
       */
      status?: string;
      /**
       * Active Sessions
       * @default 0
       */
      active_sessions?: number;
      /** Load Pct */
      load_pct?: number | null;
      /** Last Seen */
      last_seen?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** NasSecret */
    NasSecret: {
      /** Secret */
      secret: string;
    };
    /**
     * NasType
     * @enum {string}
     */
    NasType: "switch" | "ac" | "ap";
    /** NasUpdate */
    NasUpdate: {
      /** Name */
      name: string;
      /** Nasname */
      nasname: string;
      /** @default switch */
      type?: components["schemas"]["NasType"];
      /**
       * Area
       * @default
       */
      area?: string;
      /** Capacity */
      capacity?: number | null;
      /**
       * Baseline Enabled
       * @default true
       */
      baseline_enabled?: boolean;
      /**
       * Notes
       * @default
       */
      notes?: string;
      /** Secret */
      secret?: string | null;
    };
    /** NasWriteResult */
    NasWriteResult: {
      device: components["schemas"]["NasOut"];
      /** Reload Required */
      reload_required: boolean;
    };
    /** PolicyCreate */
    PolicyCreate: {
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /**
       * Description
       * @default
       */
      description?: string;
      /**
       * Scope Dept
       * @default
       */
      scope_dept?: string;
      /** @default peap-mschapv2 */
      eap_method?: components["schemas"]["EapMethod"];
      /** Vlan Id */
      vlan_id: number;
      /**
       * Acl Name
       * @default
       */
      acl_name?: string;
      /** Session Timeout S */
      session_timeout_s?: number | null;
      /** Reauth Interval S */
      reauth_interval_s?: number | null;
      /**
       * Require Cert
       * @default false
       */
      require_cert?: boolean;
      /**
       * Require Mac Bind
       * @default false
       */
      require_mac_bind?: boolean;
      /**
       * Require Edr
       * @default false
       */
      require_edr?: boolean;
      /**
       * Time Window Enabled
       * @default false
       */
      time_window_enabled?: boolean;
      /**
       * Time From
       * Format: time
       * @default 08:00:00
       */
      time_from?: string;
      /**
       * Time To
       * Format: time
       * @default 20:00:00
       */
      time_to?: string;
      /** Rate Limit Mbps */
      rate_limit_mbps?: number | null;
      /**
       * Priority
       * @default 0
       */
      priority?: number;
      /**
       * Enabled
       * @default true
       */
      enabled?: boolean;
    };
    /** PolicyOut */
    PolicyOut: {
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /**
       * Description
       * @default
       */
      description?: string;
      /**
       * Scope Dept
       * @default
       */
      scope_dept?: string;
      /** @default peap-mschapv2 */
      eap_method?: components["schemas"]["EapMethod"];
      /** Vlan Id */
      vlan_id: number;
      /**
       * Acl Name
       * @default
       */
      acl_name?: string;
      /** Session Timeout S */
      session_timeout_s?: number | null;
      /** Reauth Interval S */
      reauth_interval_s?: number | null;
      /**
       * Require Cert
       * @default false
       */
      require_cert?: boolean;
      /**
       * Require Mac Bind
       * @default false
       */
      require_mac_bind?: boolean;
      /**
       * Require Edr
       * @default false
       */
      require_edr?: boolean;
      /**
       * Time Window Enabled
       * @default false
       */
      time_window_enabled?: boolean;
      /**
       * Time From
       * Format: time
       * @default 08:00:00
       */
      time_from?: string;
      /**
       * Time To
       * Format: time
       * @default 20:00:00
       */
      time_to?: string;
      /** Rate Limit Mbps */
      rate_limit_mbps?: number | null;
      /**
       * Priority
       * @default 0
       */
      priority?: number;
      /**
       * Enabled
       * @default true
       */
      enabled?: boolean;
      /** Id */
      id: number;
      /** Vlan Name */
      vlan_name: string | null;
      /** User Count */
      user_count: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** PolicyReorder */
    PolicyReorder: {
      /** Order */
      order: number[];
    };
    /** PolicyToggle */
    PolicyToggle: {
      /** Enabled */
      enabled: boolean;
    };
    /** PolicyUpdate */
    PolicyUpdate: {
      /** Name */
      name: string;
      /** Slug */
      slug: string;
      /**
       * Description
       * @default
       */
      description?: string;
      /**
       * Scope Dept
       * @default
       */
      scope_dept?: string;
      /** @default peap-mschapv2 */
      eap_method?: components["schemas"]["EapMethod"];
      /** Vlan Id */
      vlan_id: number;
      /**
       * Acl Name
       * @default
       */
      acl_name?: string;
      /** Session Timeout S */
      session_timeout_s?: number | null;
      /** Reauth Interval S */
      reauth_interval_s?: number | null;
      /**
       * Require Cert
       * @default false
       */
      require_cert?: boolean;
      /**
       * Require Mac Bind
       * @default false
       */
      require_mac_bind?: boolean;
      /**
       * Require Edr
       * @default false
       */
      require_edr?: boolean;
      /**
       * Time Window Enabled
       * @default false
       */
      time_window_enabled?: boolean;
      /**
       * Time From
       * Format: time
       * @default 08:00:00
       */
      time_from?: string;
      /**
       * Time To
       * Format: time
       * @default 20:00:00
       */
      time_to?: string;
      /** Rate Limit Mbps */
      rate_limit_mbps?: number | null;
      /**
       * Priority
       * @default 0
       */
      priority?: number;
      /**
       * Enabled
       * @default true
       */
      enabled?: boolean;
    };
    /** ReauthorizeRequest */
    ReauthorizeRequest: {
      /** Session Ids */
      session_ids: string[];
      /**
       * Confirm
       * @default false
       */
      confirm?: boolean;
    };
    /** ReauthorizeResult */
    ReauthorizeResult: {
      /** Reauthorized */
      reauthorized: number;
      /** Failed */
      failed: components["schemas"]["DisconnectFailure"][];
    };
    /** RecentAuth */
    RecentAuth: {
      /**
       * Time
       * Format: date-time
       */
      time: string;
      /** Reply */
      reply: string;
      /** Reason */
      reason?: string | null;
      /** Reason Key */
      reason_key?: string | null;
      /** Nas Ip */
      nas_ip: string;
      /** Mac */
      mac: string;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /** Refresh Token */
      refresh_token: string;
    };
    /** SessionDetailOut */
    SessionDetailOut: {
      /** Acct Unique Id */
      acct_unique_id: string;
      /** Acct Session Id */
      acct_session_id: string;
      /** Username */
      username: string;
      /** Name */
      name: string;
      /** Dept */
      dept: string;
      /** Mac */
      mac: string;
      /** Method */
      method: string;
      /** Nas Name */
      nas_name: string;
      /** Nas Area */
      nas_area: string;
      /** Nas Ip */
      nas_ip: string;
      /** Nas Port */
      nas_port: string;
      /** Called */
      called: string;
      /** Ip */
      ip: string;
      /** Vlan */
      vlan: string;
      /** Vlan Label */
      vlan_label: string;
      /** Auth Method */
      auth_method: string;
      /** Duration S */
      duration_s: number;
      /** Status */
      status: string;
      /** Filter Id */
      filter_id: string;
      /** Session Timeout */
      session_timeout: string;
      /**
       * Start
       * Format: date-time
       */
      start: string;
      /** Bytes In */
      bytes_in: number;
      /** Bytes Out */
      bytes_out: number;
      /** Attributes */
      attributes?: {
        [key: string]: unknown;
      };
    };
    /** SettingsOut */
    SettingsOut: {
      /** Radius Auth Port */
      radius_auth_port: number;
      /** Radius Acct Port */
      radius_acct_port: number;
      /** Coa Port */
      coa_port: number;
      /** Alerts Enabled */
      alerts_enabled: boolean;
      /** Audit Enabled */
      audit_enabled: boolean;
    };
    /** SettingsUpdate */
    SettingsUpdate: {
      /** Radius Auth Port */
      radius_auth_port: number;
      /** Radius Acct Port */
      radius_acct_port: number;
      /** Coa Port */
      coa_port: number;
      /** Alerts Enabled */
      alerts_enabled: boolean;
      /** Audit Enabled */
      audit_enabled: boolean;
      /**
       * Confirm
       * @default false
       */
      confirm?: boolean;
    };
    /** SettingsWriteResult */
    SettingsWriteResult: {
      settings: components["schemas"]["SettingsOut"];
      /** Radius Reload Required */
      radius_reload_required: boolean;
    };
    /**
     * StatusAction
     * @enum {string}
     */
    StatusAction: "enable" | "disable";
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /** Refresh Token */
      refresh_token: string;
      /** Expires In */
      expires_in: number;
      /**
       * Token Type
       * @default bearer
       */
      token_type?: string;
      user: components["schemas"]["AdminProfile"];
    };
    /** UserDetail */
    UserDetail: {
      /** Id */
      id: number;
      /** Account */
      account: string;
      /** Name */
      name: string;
      /** Dept */
      dept: string;
      /** Title */
      title: string;
      status: components["schemas"]["UserStatus"];
      /** Locked Until */
      locked_until: string | null;
      /** Policy Id */
      policy_id: number | null;
      /** Policy Name */
      policy_name: string | null;
      source: components["schemas"]["UserSource"];
      /** Endpoint Count */
      endpoint_count: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Endpoints */
      endpoints: components["schemas"]["EndpointBrief"][];
      /** Recent Auth */
      recent_auth?: components["schemas"]["RecentAuth"][];
      /**
       * Policy Rules
       * @description 编译后的 FreeRADIUS 属性清单
       */
      policy_rules?: string[];
    };
    /** UserPolicyRequest */
    UserPolicyRequest: {
      /** Accounts */
      accounts: string[];
      /** Policy Id */
      policy_id: number;
    };
    /**
     * UserSource
     * @enum {string}
     */
    UserSource: "ad" | "local";
    /**
     * UserStatus
     * @enum {string}
     */
    UserStatus: "active" | "disabled" | "locked";
    /** UserStatusRequest */
    UserStatusRequest: {
      /** Accounts */
      accounts: string[];
      action: components["schemas"]["StatusAction"];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Login */
  login_api_auth_login_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Refresh */
  refresh_api_auth_refresh_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefreshRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["TokenResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Logout */
  logout_api_auth_logout_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogoutRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Me */
  me_api_auth_me_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AdminProfile"];
        };
      };
    };
  };
  /** Change My Password */
  change_my_password_api_auth_me_password_put: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangePasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Admins */
  list_admins_api_auth_admins_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AdminOut"][];
        };
      };
    };
  };
  /** Create Admin */
  create_admin_api_auth_admins_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["AdminOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Admin */
  delete_admin_api_auth_admins__admin_id__delete: {
    parameters: {
      path: {
        admin_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Admin */
  update_admin_api_auth_admins__admin_id__patch: {
    parameters: {
      path: {
        admin_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AdminUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AdminOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Users */
  list_users_api_users_get: {
    parameters: {
      query?: {
        dept?: string | null;
        status?: components["schemas"]["UserStatus"] | null;
        /** @description policy_group id */
        policy?: number | null;
        q?: string | null;
        page?: number;
        size?: number;
        sort?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get User */
  get_user_api_users__account__get: {
    parameters: {
      path: {
        account: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["UserDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Trigger Ad Sync
   * @description Trigger an incremental AD sync (async — returns immediately).
   *
   * The sync runs in a tracked background task on its own session so the
   * request is not held open and failures are logged. Poll
   * ``GET /api/users/sync-records`` to track progress.
   */
  trigger_ad_sync_api_users_sync_ad_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AdSyncResult"];
        };
      };
    };
  };
  /**
   * List Sync Records
   * @description List AD sync job history (latest first).
   */
  list_sync_records_api_users_sync_records_get: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Sync Record
   * @description Detail of a single AD sync job (includes error text).
   */
  get_sync_record_api_users_sync_records__job_id__get: {
    parameters: {
      path: {
        job_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AdSyncJobOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update User Status */
  update_user_status_api_users_status_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserStatusRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Affected"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Assign User Policy */
  assign_user_policy_api_users_policy_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserPolicyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Affected"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Policies */
  list_policies_api_policies_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PolicyOut"][];
        };
      };
    };
  };
  /** Create Policy */
  create_policy_api_policies_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PolicyCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["PolicyOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Policy */
  get_policy_api_policies__policy_id__get: {
    parameters: {
      path: {
        policy_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PolicyOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Policy */
  update_policy_api_policies__policy_id__put: {
    parameters: {
      path: {
        policy_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PolicyUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PolicyOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Policy */
  delete_policy_api_policies__policy_id__delete: {
    parameters: {
      path: {
        policy_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Toggle Policy */
  toggle_policy_api_policies__policy_id__patch: {
    parameters: {
      path: {
        policy_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PolicyToggle"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PolicyOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reorder Policies */
  reorder_policies_api_policies_reorder_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["PolicyReorder"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PolicyOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Nas */
  list_nas_api_devices_nas_get: {
    parameters: {
      query?: {
        type?: components["schemas"]["NasType"] | null;
        area?: string | null;
        /** @description online/offline/high-load; derived from radpostauth/radacct (docs/02) */
        status?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Nas */
  create_nas_api_devices_nas_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NasCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["NasWriteResult"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Delete Nas */
  delete_nas_api_devices_nas__device_id__delete: {
    parameters: {
      path: {
        device_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Nas */
  update_nas_api_devices_nas__device_id__patch: {
    parameters: {
      path: {
        device_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NasUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NasWriteResult"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Reveal Nas Secret */
  reveal_nas_secret_api_devices_nas__device_id__secret_get: {
    parameters: {
      path: {
        device_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["NasSecret"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Nas Ports */
  nas_ports_api_devices_nas__device_id__ports_get: {
    parameters: {
      path: {
        device_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
              [key: string]: unknown;
            }[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Nas Ssids */
  nas_ssids_api_devices_nas__device_id__ssids_get: {
    parameters: {
      path: {
        device_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
              [key: string]: unknown;
            }[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Endpoints */
  list_endpoints_api_devices_endpoints_get: {
    parameters: {
      query?: {
        type?: components["schemas"]["EndpointType"] | null;
        comp?: components["schemas"]["Compliance"] | null;
        q?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Create Endpoint */
  create_endpoint_api_devices_endpoints_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EndpointCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["EndpointOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Update Endpoint */
  update_endpoint_api_devices_endpoints__mac__patch: {
    parameters: {
      path: {
        mac: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EndpointUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EndpointOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Import Endpoints */
  import_endpoints_api_devices_endpoints_import_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EndpointImport"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Affected"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Remove From Whitelist */
  remove_from_whitelist_api_devices_endpoints__mac__whitelist_delete: {
    parameters: {
      path: {
        mac: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Affected"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Revoke Endpoint Cert */
  revoke_endpoint_cert_api_devices_endpoints__mac__revoke_cert_post: {
    parameters: {
      path: {
        mac: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Affected"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Sessions */
  list_sessions_api_sessions_get: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
        sort?: string | null;
        dept?: string | null;
        method?: string | null;
        nas?: string | null;
        vlan?: string | null;
        auth?: string | null;
        q?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Export Sessions Csv */
  export_sessions_csv_api_sessions_export_csv_get: {
    parameters: {
      query?: {
        dept?: string | null;
        method?: string | null;
        nas?: string | null;
        vlan?: string | null;
        auth?: string | null;
        q?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Session */
  get_session_api_sessions__acct_unique_id__get: {
    parameters: {
      path: {
        acct_unique_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SessionDetailOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Disconnect Sessions */
  disconnect_sessions_api_sessions_disconnect_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["DisconnectRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["DisconnectResult"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Reauthorize Sessions
   * @description Bulk CoA-Request to trigger re-authorization (docs/01 批量 CoA).
   */
  reauthorize_sessions_api_sessions_reauthorize_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ReauthorizeRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ReauthorizeResult"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Logs */
  list_logs_api_auth_logs_get: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
        sort?: string | null;
        result?: string | null;
        nas?: string | null;
        user?: string | null;
        reason?: string | null;
        eap?: string | null;
        from?: string | null;
        to?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Export Logs Csv */
  export_logs_csv_api_auth_logs_export_csv_get: {
    parameters: {
      query?: {
        result?: string | null;
        nas?: string | null;
        user?: string | null;
        reason?: string | null;
        eap?: string | null;
        from?: string | null;
        to?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Log */
  get_log_api_auth_logs__log_id__get: {
    parameters: {
      path: {
        log_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["LogDetailOut"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Kpis */
  get_kpis_api_dashboard_kpis_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /** Get Trend */
  get_trend_api_dashboard_trend_get: {
    parameters: {
      query?: {
        range?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Alerts */
  get_alerts_api_dashboard_alerts_get: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Read Alert */
  read_alert_api_dashboard_alerts__alert_id__read_post: {
    parameters: {
      path: {
        alert_id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Report Summary */
  report_summary_api_reports_summary_get: {
    parameters: {
      query?: {
        period?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Report Endpoint Types */
  report_endpoint_types_api_reports_endpoint_types_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /** Report Departments */
  report_departments_api_reports_departments_get: {
    parameters: {
      query?: {
        period?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Report Export */
  report_export_api_reports_export_get: {
    parameters: {
      query: {
        format: string;
        period?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Settings */
  get_settings_api_settings_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsOut"];
        };
      };
    };
  };
  /** Update Settings */
  update_settings_api_settings_put: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettingsUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsWriteResult"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Get Alert Rules */
  get_alert_rules_api_settings_alert_rules_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AlertRuleOut"][];
        };
      };
    };
  };
  /** Update Alert Rules */
  update_alert_rules_api_settings_alert_rules_put: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AlertRulesUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AlertRuleOut"][];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** List Audit */
  list_audit_api_audit_get: {
    parameters: {
      query?: {
        action?: string | null;
        actor?: string | null;
        from?: string | null;
        to?: string | null;
        page?: number;
        size?: number;
        sort?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Export Audit Csv
   * @description CSV archive of audit log entries (docs/08「审计日志」归档导出).
   */
  export_audit_csv_api_audit_export_csv_get: {
    parameters: {
      query?: {
        action?: string | null;
        from?: string | null;
        to?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health */
  health_api_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /**
   * Metrics
   * @description Prometheus metrics exporter — reserved (docs/07「M7 之后可选」).
   */
  metrics_api_metrics_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /**
   * Reload Radius
   * @description Restart FreeRADIUS so rlm_sql re-reads the nas table (docs/06).
   *
   * ``read_clients`` only loads at startup, so client changes need a restart.
   * Runs ``OPENRADIUS_RADIUS_RELOAD_COMMAND`` when configured; otherwise
   * responds in manual mode with instructions.
   */
  reload_radius_api_ops_reload_radius_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /**
   * Compile
   * @description Idempotent full recompile of policy/user state into the radius schema.
   */
  compile_api_ops_compile_post: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  /** Portal Root */
  _portal_root_api_portal_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Portal Catch All */
  _portal_catch_all_api_portal__path__get: {
    parameters: {
      path: {
        path: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
