"""domain models (M2)

Revision ID: cf9a9b67326d
Revises: 2668af2e944a
Create Date: 2026-08-12 04:22:00.676017

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'cf9a9b67326d'
down_revision: str | None = '2668af2e944a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acl_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acl_profile')),
    sa.UniqueConstraint('name', name=op.f('uq_acl_profile_name'))
    )
    op.create_table('ad_sync_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.Enum('manual', 'cron', name='synctrigger', native_enum=False, length=8), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='syncstatus', native_enum=False, length=8), nullable=False),
    sa.Column('added', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('disabled', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ad_sync_job'))
    )
    op.create_table('alert_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Enum('critical', 'warning', 'info', name='alertlevel', native_enum=False, length=8), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_event'))
    )
    op.create_index(op.f('ix_alert_event_created_at'), 'alert_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_alert_event_rule_key'), 'alert_event', ['rule_key'], unique=False)
    op.create_table('alert_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('threshold_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rule')),
    sa.UniqueConstraint('key', name=op.f('uq_alert_rule_key'))
    )
    op.create_table('nas_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('nasname', sa.String(length=45), nullable=False),
    sa.Column('type', sa.Enum('switch', 'ac', 'ap', name='nastype', native_enum=False, length=8), nullable=False),
    sa.Column('area', sa.String(length=128), nullable=False),
    sa.Column('secret_enc', sa.String(length=128), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('baseline_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=False),
    sa.Column('radius_nas_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nas_device')),
    sa.UniqueConstraint('name', name=op.f('uq_nas_device_name'))
    )
    op.create_index(op.f('ix_nas_device_nasname'), 'nas_device', ['nasname'], unique=True)
    op.create_table('system_setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_setting'))
    )
    op.create_table('vlan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vlan')),
    sa.UniqueConstraint('vid', name=op.f('uq_vlan_vid'))
    )
    op.create_table('policy_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('scope_dept', sa.String(length=128), nullable=False),
    sa.Column('eap_method', sa.Enum('eap-tls', 'peap-mschapv2', name='eapmethod', native_enum=False, length=16), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=False),
    sa.Column('acl_name', sa.String(length=64), nullable=False),
    sa.Column('session_timeout_s', sa.Integer(), nullable=True),
    sa.Column('reauth_interval_s', sa.Integer(), nullable=True),
    sa.Column('require_cert', sa.Boolean(), nullable=False),
    sa.Column('require_mac_bind', sa.Boolean(), nullable=False),
    sa.Column('require_edr', sa.Boolean(), nullable=False),
    sa.Column('time_window_enabled', sa.Boolean(), nullable=False),
    sa.Column('time_from', sa.Time(), nullable=False),
    sa.Column('time_to', sa.Time(), nullable=False),
    sa.Column('rate_limit_mbps', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlan.id'], name=op.f('fk_policy_group_vlan_id_vlan')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_group')),
    sa.UniqueConstraint('name', name=op.f('uq_policy_group_name'))
    )
    op.create_index(op.f('ix_policy_group_priority'), 'policy_group', ['priority'], unique=False)
    op.create_index(op.f('ix_policy_group_slug'), 'policy_group', ['slug'], unique=True)
    op.create_index(op.f('ix_policy_group_vlan_id'), 'policy_group', ['vlan_id'], unique=False)
    op.create_table('access_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('dept', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('active', 'disabled', 'locked', name='userstatus', native_enum=False, length=16), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('policy_group_id', sa.Integer(), nullable=True),
    sa.Column('ad_dn', sa.String(length=512), nullable=True),
    sa.Column('ad_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Enum('ad', 'local', name='usersource', native_enum=False, length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['policy_group_id'], ['policy_group.id'], name=op.f('fk_access_user_policy_group_id_policy_group'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_user'))
    )
    op.create_index(op.f('ix_access_user_account'), 'access_user', ['account'], unique=True)
    op.create_index(op.f('ix_access_user_dept'), 'access_user', ['dept'], unique=False)
    op.create_index(op.f('ix_access_user_policy_group_id'), 'access_user', ['policy_group_id'], unique=False)
    op.create_index(op.f('ix_access_user_status'), 'access_user', ['status'], unique=False)
    op.create_table('endpoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('etype', sa.Enum('laptop', 'phone', 'printer', 'camera', 'other', name='endpointtype', native_enum=False, length=8), nullable=False),
    sa.Column('compliance', sa.Enum('ok', 'warn', 'bad', 'white', name='compliance', native_enum=False, length=8), nullable=False),
    sa.Column('comp_detail', sa.String(length=255), nullable=False),
    sa.Column('cert_serial', sa.String(length=128), nullable=True),
    sa.Column('cert_not_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('whitelisted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['access_user.id'], name=op.f('fk_endpoint_owner_user_id_access_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_endpoint'))
    )
    op.create_index(op.f('ix_endpoint_mac'), 'endpoint', ['mac'], unique=True)
    op.create_index(op.f('ix_endpoint_owner_user_id'), 'endpoint', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###

    # PG-only objects consumed by FreeRADIUS server-side SQL (docs/06);
    # SQLite dev skips them (docs/04「Alembic autogenerate」).
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE OR REPLACE FUNCTION public.norm_mac(text) RETURNS text AS $$
              SELECT upper(regexp_replace($1, '[-.]', ':', 'g'))
            $$ LANGUAGE sql IMMUTABLE
            """
        )
        op.execute(
            """
            CREATE OR REPLACE VIEW public.v_user_policy_flags AS
            SELECT b.account,
                   concat_ws(',',
                     CASE WHEN b.require_mac_bind THEN 'mac' END,
                     CASE WHEN b.require_edr THEN 'edr' END,
                     CASE WHEN b.time_window_enabled
                          THEN 'time:' || to_char(b.time_from, 'HH24:MI')
                               || '-' || to_char(b.time_to, 'HH24:MI') END
                   ) AS flags_csv
            FROM (
              SELECT DISTINCT ON (u.account)
                     u.account, p.require_mac_bind, p.require_edr,
                     p.time_window_enabled, p.time_from, p.time_to
              FROM access_user u
              JOIN policy_group p ON p.id = u.policy_group_id
              WHERE p.enabled AND u.status = 'active'
              ORDER BY u.account, p.priority DESC
            ) b
            """
        )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP VIEW IF EXISTS public.v_user_policy_flags")
        op.execute("DROP FUNCTION IF EXISTS public.norm_mac(text)")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoint_owner_user_id'), table_name='endpoint')
    op.drop_index(op.f('ix_endpoint_mac'), table_name='endpoint')
    op.drop_table('endpoint')
    op.drop_index(op.f('ix_access_user_status'), table_name='access_user')
    op.drop_index(op.f('ix_access_user_policy_group_id'), table_name='access_user')
    op.drop_index(op.f('ix_access_user_dept'), table_name='access_user')
    op.drop_index(op.f('ix_access_user_account'), table_name='access_user')
    op.drop_table('access_user')
    op.drop_index(op.f('ix_policy_group_vlan_id'), table_name='policy_group')
    op.drop_index(op.f('ix_policy_group_slug'), table_name='policy_group')
    op.drop_index(op.f('ix_policy_group_priority'), table_name='policy_group')
    op.drop_table('policy_group')
    op.drop_table('vlan')
    op.drop_table('system_setting')
    op.drop_index(op.f('ix_nas_device_nasname'), table_name='nas_device')
    op.drop_table('nas_device')
    op.drop_table('alert_rule')
    op.drop_index(op.f('ix_alert_event_rule_key'), table_name='alert_event')
    op.drop_index(op.f('ix_alert_event_created_at'), table_name='alert_event')
    op.drop_table('alert_event')
    op.drop_table('ad_sync_job')
    op.drop_table('acl_profile')
    # ### end Alembic commands ###
